"""add topic_candidates and user_topic_sessions

Revision ID: 2200fe6d09ac
Revises: c68768ce3c3e
Create Date: 2025-11-17 20:17:46.401283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2200fe6d09ac'
down_revision: Union[str, Sequence[str], None] = 'c68768ce3c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interest_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_candidates_category_id'), 'topic_candidates', ['category_id'], unique=False)
    op.create_table('user_topic_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('input_keyword', sa.String(length=1000), nullable=True),
    sa.Column('use_trend', sa.Boolean(), nullable=False),
    sa.Column('selected_format', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_topic_sessions_topic_id'), 'user_topic_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_sessions_user_id'), 'user_topic_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_topic_sessions_user_id'), table_name='user_topic_sessions')
    op.drop_index(op.f('ix_user_topic_sessions_topic_id'), table_name='user_topic_sessions')
    op.drop_table('user_topic_sessions')
    op.drop_index(op.f('ix_topic_candidates_category_id'), table_name='topic_candidates')
    op.drop_table('topic_candidates')
    # ### end Alembic commands ###
