"""add trend_score_to_topic_candidates

Revision ID: 5a909fc72b10
Revises: f9b83ec6aaa1
Create Date: 2025-11-17 23:05:02.534777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a909fc72b10'
down_revision: Union[str, Sequence[str], None] = 'f9b83ec6aaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
