"""add topic_candidates and user_topic_sessions

Revision ID: b94e44c1c97e
Revises: 2200fe6d09ac
Create Date: 2025-11-17 21:29:13.160992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94e44c1c97e'
down_revision: Union[str, Sequence[str], None] = '2200fe6d09ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
