"""add trend_score_to_topic_candidates

Revision ID: f9b83ec6aaa1
Revises: b94e44c1c97e
Create Date: 2025-11-17 22:34:59.779727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b83ec6aaa1'
down_revision: Union[str, Sequence[str], None] = 'b94e44c1c97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_candidates', sa.Column('trend_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_candidates', 'trend_score')
    # ### end Alembic commands ###
